version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 82:81
    depends_on:
      - db


  grafana:
    image: grafana/grafana:8.4.5
    container_name: grafana
    ports:
     - 3000:81
    depends_on:
     - db
    restart: unless-stopped

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
     - '80:81'
     - '81:81'
     - '443:443'
    depends_on:
     - app
     - grafana
    volumes:
     - ./data:/data
     - ./letsencrypt:/etc/letsencrypt
