name: CI/CD project Jusan

on:
  push:
    branches: [ "devops" ]
  pull_request:
    branches: [ "devops" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: docker compose test
      run:  chmod +x /test.sh
         ./test.sh
      shell: bash 

    - name: kuber app
      run: kubectl apply -f app.yaml

    - name: kuber db
      run: kubectl apply -f db.yaml

    - name: kube grafana
      run: kubectl apply -f grafana.yaml



  # push:
  
  #   runs-on: ubuntu-latest
    
    
  #   steps:
  #   - name: install ssh keys
  #     run: install -m 600 -D /dev/null ~/.ssh/id_rsa
       
        

  #   - name: test connction
  #     run:
  #        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #   - name: test connction2
  #     run:
  #       ssh-keyscan -p 2222 -H 45.8.119.241  > ~/.ssh/known_hosts
  #   - name: —Åonnect and pull
  #     run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p 2222 "cd /jusan/examSingularity1  && git pull https://github.com/Smagicom/examSingularity.git  devops && exit"
      
    # - name: cleanup
    #   run: rm -rf ~/.ssh
   
    
