name: CI/CD project Jusan

on:
  push:
    branches: [ "devops" ]
  pull_request:
    branches: [ "devops" ]

jobs:


   


  push:
  
    runs-on: ubuntu-latest
    
    
    steps:
    - name: install ssh keys
      run: install -m 600 -D /dev/null ~/.ssh/id_rsa
       
        

    - name: test connction
      run:
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    - name: test connction2
      run:
        ssh-keyscan -p 2222 -H 45.8.119.241  > ~/.ssh/known_hosts
    - name: —Åonnect and pull
      run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
            cd /jusan/examSingularity &&
            git fetch origin devops &&
            git checkout devops &&
            git pull origin devops &&
            exit
          EOF
      
    - name: cleanup
      run: rm -rf ~/.ssh
   
    
