name: test CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  push:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: create ssh keys
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa

      - name: write ssh private key
        run: echo "${{ secret.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: add to known hosts
        run: ssh-keyscan -p ${{ secret.SSH_PORT }} -H ${{ secret.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect and pull 
        run: ssh ${{ secret.SSH_USER }}@${{ secret.SSH_HOST }} -p ${{ secret.SSH_PORT }} "cd /opt/ && git clone https://github.com/Smagicom/examSingularity.git main && echo "docker build" && exit"

      - name: clean
        run: rm -rf ~/.ssh
