name: CI/CD project Jusan

on:
  push:
    branches: [ "devops" ]
  pull_request:
    branches: [ "devops" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name : Kubernetes app
      run: kubectl apply -f app.yaml

    - name: Kubernetes db
      run: kubectl apply -f db.yaml

    - name: Kubernetes grafana
      run: kubectl apply -f grafana.yaml
      
   


  push:
  
    runs-on: ubuntu-latest
    
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}} -p ${{secrets.SSH_PORT }} "cd  /jusan/examSingularity && git checkout  https://https://github.com/Smagicom/examSingularity/tree/main && git pull && exit"
      
    - name: cleanup
      run: rm -rf ~/.ssh
   
    
