name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d --build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: test
       run: echo "test"
  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: install ssh keys
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa
      - name: ssh private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - name: add known hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "cd /opt/ && git clone https://github.com/Smagicom/examSingularity.git && cd /examSingularity && docker-compose up -d --build"
      - name: clean
        run: rm -rf ~/.ssh
    
