name: CI/CD project Jusan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  
      

  push:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}} -p ${{secrets.SSH_PORT }} "cd  /jusan/examSingularity && git checkout  https://https://github.com/Smagicom/examSingularity/tree/main && git pull && exit"
      
    - name: cleanup
      run: rm -rf ~/.ssh
   
    
