name: CI/CD project Jusan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker compose up -d

    - name : Kubernetes app
      run: kubectl apply -f app.yaml

    - name: Kubernetes db
      run: kubectl apply -f db.yaml

    - name: Kubernetes grafana
      run: kubectl apply -f grafana.yaml
    
